### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by darkx239** [LouisK130/Orange-Cosmos-Roleplay#5]
Is there anyway you can add money to a character or yourself

**Comment by LouisK130** [comment]
Yes, but it's not too simple since I didn't want to encourage admin abuse. It requires access to the server console and manually editing the SQL database. There are many tools (Google HeidiSQL for example) that let you view and edit SQL.

Ensure that you are disconnected from the server. If you were online in the past 15 minutes you need to open the server console and run "ocrp_forcesqlpush"

Then, connect to the SQL database and open ocrp_users table. Find the row with your SteamID and change the "wallet" and "bank" rows to whatever you'd like. Save the changes.

Reconnect to the server and you should see the changes. Changes you make the a player's data will be overwritten if the player is online or was recently online when you edited the database. You must make sure they disconnect and you run the "ocrp_forcesqlpush" command before updating the database.

I could add a command to simplify this process if it's a popular idea, but like I said I feel it promotes admin abuse.

**Comment by darkx239** [comment]
ok was afk watching family guy and also its not that i want to admin abuse its just i play darkrp sometimes and it bugs out and gives me 1e+647$
