### ISSUE TITLE
VCMod question

### ISSUE THREAD

**Issue by clunkyy** [LouisK130/Orange-Cosmos-Roleplay#65]
I have the most updated version of VCMod, will vehicles work?

**Comment by LouisK130** [comment]
The gamemode is untested with any versions of VCMod beyond the one posted in the readme. Parts of the gamemode rely directly on parts of VCMod that have since been removed, I highly doubt it will function with the newest version.

If I have time, I'll try to look into supporting newer versions of VCMod, but I can't promise anything.
